[pytest]
pythonpath = .
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Фильтрация предупреждений
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning

# Опции вывода
addopts = 
    -v
    --strict-markers
    --tb=short
    --disable-warnings
    --cov=app
    --cov-report=term-missing