[pytest]
# pytest видит папку app
pythonpath = .

# Авторежим (решение проблемы с PytestRemovedIn9Warning)
asyncio_mode = auto

# Настройки поиска тестов
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Игнорирование технических предупреждений
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::pytest.PytestRemovedIn9Warning

# Опции вывода
addopts = 
    -v
    --strict-markers
    --tb=short
    --disable-warnings